version: 0.2
run-as: root
env:
  shell: bash
phases: 
  pre_build:
    commands:
      - echo 'prebuild stage installing node /npm modules'
  build:
    commands:
      - env
      #- npm run build



