pipeline{
   agent any
   stages{
          stage('Build') {
              
            steps {      
                   shell(readFileFromWorkspace('run-container.sh'))
            }
        }   
   }
}
