pipeline{
   agent any
   stages{
          stage('Build') {
              
            steps {      
                  sh '''
                     echo $PWD
                     ./django/run-container.sh
                     '''
            }
        }   
   }
}
